[package]
name = "nhtml-gateway"
version = "0.7.1"
edition = "2021"
license = "MIT OR AGPL-3.0-only OR LicenseRef-Commercial"
[lib]
name = "nhtml_gateway"
path = "src/lib.rs"

[[bin]]
name = "nhtml"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
tokio-tungstenite = "0.24"
reqwest = { version = "0.11", features = ["json"] }
clap = { version = "4.4", features = ["derive"] }
notify = "6.1.1"
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "sqlite", "mysql", "postgres", "macros", "chrono", "uuid"] }
zstd = "0.13"
crc32fast = "1.3"
hex = "0.4"
axum = { version = "0.7", features = ["ws"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
toml = "0.8"
urlencoding = "2.1"
tracing = "0.1"
scraper = "0.18"
tracing-subscriber = { version = "0.3", features = ["json"] }
url = "2.5"
mime_guess = "2.0"
hmac = "0.12"
sha2 = "0.10"
getrandom = { version = "0.2", features = ["js"] }
fastcgi-client = { version = "0.11", features = ["runtime-tokio"] }
redis = { version = "1.2", features = ["tokio-comp"] }
metrics = "0.22"
metrics-exporter-prometheus = "0.12"
html-escape = "0.2"
lru = "0.12"
