# content/browser/loader/nhtml/BUILD.gn
import("//build/config/features.gni")

source_set("nhtml_browser") {
  sources = [
    "nhtml_url_loader_throttle.cc",
    "nhtml_url_loader_throttle.h",
  ]

  deps = [
    "//base",
    "//content/common/nhtml:nhtml_common",
    "//content/public/browser",
    "//net",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
  ]
}
